name: motionplay
channels:
  - conda-forge
dependencies:
  - python=3.10
  - opencv
  - numpy<2
  - pip
  - pip:
      - mediapipe==0.10.14
      - scikit-learn
      - pandas
      - joblib
      - pynput
